pipeline {
    agent any
    // enviroment {
    //     DEFAULT_DIR = "/var/betterme/script"
    // }
    stages {
        stage("Prepare Update") {
            steps {
                dir("/var/better/script") {
                    echo "[INFO] Prepare Stage"
                    sh "nvm use 17"
                    echo "Use Node v17"
                }
            }
        }
        stage("Run Frontend") {
            steps {
                
                echo "[INFO] Run Frontend"

            }
        }
    }
}