pipeline {
    agent any
    // enviroment {
    //     DEFAULT_DIR = "/var/betterme/script"
    // }
    stages {
        stage("Prepare Update") {
            steps {
                dir("/var/better/script") {
                    echo "[INFO] Prepare Stage"
                    sh "bash prepare_update.sh"
                    echo "Use Node v17"
                }
            }
        }
        stage("Run Frontend") {
            steps {
                dir("/var/better/script") {
                    echo "[INFO] Run Frontend"
                    sh "bash run_frontend.sh"
                }
            }
        }
        stage("Run Backend") {
            steps {
                dir("/var/better/script") {
                    echo "[INFO] Run Backend"
                    sh "bash run_backend.sh"
                }
            }
        }
    }
}